spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/itemsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO
