spring:
  datasource:
    url: jdbc:h2:mem:ordersdb 
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      itemService:
        registerHealthIndicator : true
        slidingWindowSize : 5
        failureRateThreshold : 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      itemService:
        maxAttempts : 5
        waitDuration : 2s
  
  
