spring:
  kafka:
    bootstrap-servers: localhost:9092

    # Producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Consumer configuration
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # required to deserialize your DTO
        spring.json.value.default.type: com.example.order.dto.ItemDTO
  
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
    loadbalancer:
      retry:
        enabled: false

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.cache: TRACE

resilience4j:
  circuitbreaker:
    instances:
      itemBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        recordExceptions:
          - java.lang.RuntimeException

  retry:
    instances:
      itemRetry:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      itemService:
        timeoutDuration: 2s
        
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
