spring:
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    io.github.resilience4j.circuitbreaker : DEBUG
    io.github.resilience4j.retry :  DEBUG

resilience4j:
  circuitbreaker:
    instances:
      ItemClient#getItemById(Long):
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        recordExceptions:
          - feign.FeignException
          - java.lang.RuntimeException
  retry:
    instances:
      ItemClient#getItemById(Long):
        maxAttempts: 5
        waitDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
